### ISSUE TITLE
system_interrupt.c -> bugs / remarques / améliorations

### ISSUE THREAD

**Issue by PBYetml** [CyrilFeliciano/MINF_TP0#2]
- [x] => type => librairie => déclaration => type normalisé
https://github.com/CyrilFeliciano/MINF_TP0/blob/5063d10c1f05799f8bed16ef743f1ce8c84e2c1c/firmware/src/system_config/default/system_interrupt.c#L76
- [x] => question => appel de fonction => MAJ flag interrupt => l'appel de fonction se fait au début ou à la fin ?
https://github.com/CyrilFeliciano/MINF_TP0/blob/5063d10c1f05799f8bed16ef743f1ce8c84e2c1c/firmware/src/system_config/default/system_interrupt.c#L78
- [x] => algorithme => timing => gestion des "etats" => demande du CDC respecté ?! 
- [x] => question => algorithme => combien d'itération faites-vous dans le bloc if ?
- [x] => question => que ce passe-t-il quand `compteurEtat`  vaut 30 ?
https://github.com/CyrilFeliciano/MINF_TP0/blob/5063d10c1f05799f8bed16ef743f1ce8c84e2c1c/firmware/src/system_config/default/system_interrupt.c#L80C1-L87C6

**Comment by PBYetml** [comment]
Merci Cyril pour le live -> comme discuté l'algorithme n'est pas forcément faux, mais il n'est pas sécure !! 

- [x] => déclaration du if => condition/test => évitez le == car qu'une seule valeur testée !!!

**Comment by CyrilFeliciano** [comment]
1. La manière d’inclure la librairie dans le fichier app.h n'est pas fausse, mais pour aider à la compréhension et respecté les normes du C, je devrais inclure la librairie "stdint.h" dans le fichier d'interruption.

2. L'appel de la fonction de MAJ flag interrupt doit se faire à la fin de l'interruption, afin de garantir que tout le code lié à l'interruption soit effectué. En la mettant au début, il y a un risque qu'une autre interruption (autres timers) interviennent et empêche le code de s’exécuter comme voulu. Il serais donc préférable de mettre l'appel de cette fonction à la fin de la routine d'interruption.

3. Comme discuté dans l'appel vidéo, mon code n'est pas faux mais je pourrais faire des changements afin d'augmenté la sécurité de celui-ci. J'aurais du mettre ">= 29", afin de garantir que si il y a un bug et que le compteur vaut 30, l'état sera mis a jour vers "APP_STATE_SERVICE_TASKS". 

4. Une fois que la valeur du compteurEtat est égal ou supérieur à "29", il y aura une seule itération toutes les 100 [ms] (interruption du timer1).

5. L'état de la machine d'état ne sera plus mis à jour vers l'état "APP_STATE_SERVICE_TASKS". Voir point 3 pour les changements apportés.

6. Comme expliqué dans le point 3, j'ai changé le "==" en ">=" afin de tester plusieurs valeurs. Si pour un bug, mon compteur vaudrait "30" l'état serait quand même mis à jour.

J'ai apporté toutes les modifications citées plus haut dans mon code se trouvant sur Github.
